name: Node CI
on: [push]
job:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      use: actions/checkout@v4
    - name: npm
      run: |
        npm install
        npm run build
    - name: artifacts
      use: actions/upload-artifact@v4
      with:
        name: dist
        path:
          dist
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: upload
        path: dist
